[package]
name = "mirage"
version = "0.1.0"
authors = ["Alex Silva <alex@unendli.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1"
